spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  cloud:
    config:
      server:
        #native:
        #  search-locations: "classpath:/config"
        git:
          uri: "https://github.com/Oswe-gif/Java-Course-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

server:
  port: 8071